version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: gts_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gts_bot
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  worker:
    image: ldngduong/getpocket-worker:latest
    container_name: gts_worker
    restart: always
    ports:
      - "5001:5001"
    depends_on:
      - db

volumes:
  postgres_data:
